name: Update github myprofile

on: 'page_build'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        cd ./github_myprofile_updater
        python3 update.py
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        # git config --local user.email "${{ secrets.MY_EMAIL }}"  用系统默认变量代替密码变量
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        # export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GHRS_GITHUB_API_TOKEN }}@github.com/yinjiewang/yinjiewang.git"  用系统默认变量代替密码变量
        # 将主页中的部分内容生成MD文件更新到yinjiewang仓库
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/yinjiewang/yinjiewang.git"
        git add README.md
        git add images
        git commit -m "update my description automatically"
        git push "${remote_repo}" HEAD:main --force
